let mainDiv=document.createElement("div");
document.body.appendChild(mainDiv);
mainDiv.style.display="flex";
mainDiv.style.flexWrap="wrap";
let div1=document.createElement("div");
let div2=document.createElement("div");
let div3=document.createElement("div");
let div4=document.createElement("div");
mainDiv.appendChild(div1);
mainDiv.appendChild(div2);
mainDiv.appendChild(div3);
mainDiv.appendChild(div4);
mainDiv.style.width="200px";
mainDiv.style.height="200px";
div1.style.backgroundColor="red";
div2.style.backgroundColor="blue";
div3.style.backgroundColor="green";
div4.style.backgroundColor="yellow";
div1.style.width="100px";
div1.style.height="100px";
div2.style.width="100px";
div2.style.height="100px";
div3.style.width="100px";
div3.style.height="100px";
div4.style.width="100px";
div4.style.width="100px";
div1.style.borderRadius=" 0 0 100px 0";
div1.style.transform="rotate(180deg)";
div2.style.borderRadius=" 0 100px 0 0";
// div2.style.transform="rotate(0 deg)";
div3.style.borderRadius=" 0 0 0px 100px";
// div3.style.transform="rotate(0deg)";
div4.style.borderRadius=" 0 0 100px 0";
// div4.style.transform="rotate(0deg)";
document.mainDiv.style.justifyContent="center";
